# Generated by Django 6.0.4 on 2026-04-13 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_active_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_courses', to='webapp.video'),
        ),
    ]
