# Generated by Django 6.0.4 on 2026-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_course_last_active_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='html_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
