# Generated by Django 6.0.4 on 2026-04-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_video_html_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='quiz_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
